### ISSUE TITLE
Theme "not working"

### ISSUE THREAD

**Issue by niklasfink** [wesbos/Cobalt2-Slack#3]
Hey, when pasting the color values into Slack, it doesn't make it look like on your screenshot. Maybe Slack added some more color fields and therefore it doesn't match anymore?

![image](https://user-images.githubusercontent.com/1809301/31919305-1a8e5aee-b8ad-11e7-8e5e-7da5f281d3f8.png)

**Comment by niklasfink** [comment]
(hover is also blue instead of yellow)

**Comment by ianizaguirre** [comment]
@niklasfink 
I agree. I tried duplicating it from his picture and got these codes if you want to try it out:
```
#182E40,#1F4662,#1D425D,#FFFFFF,#988026,#FFFFFF,#988026,#FEBD29
```

**Comment by wesbos** [comment]
want to send a PR?

**Comment by ianizaguirre** [comment]
@wesbos 
Just Submitted a PR :-)
